# Generated by Django 3.2.9 on 2022-02-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='photo',
            field=models.ImageField(default='download.jpg', upload_to='foods/'),
        ),
    ]
