# Generated by Django 3.2.9 on 2022-03-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_alter_food_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='type_food',
            field=models.CharField(choices=[('breakfast', 'صبحانه'), ('drink', 'نوشیدنی'), ('dinner', 'شام'), ('lunch', 'ناهار')], default='drink', max_length=10, verbose_name='نوع غذا'),
        ),
    ]
