# Generated by Django 3.2.9 on 2022-03-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان دسته')),
                ('description', models.CharField(max_length=100, verbose_name='توضیحات')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان انتشار')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی')),
            ],
        ),
    ]
