# Generated by Django 3.2.9 on 2022-03-07 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='photo',
            new_name='phone',
        ),
    ]
