# Generated by Django 3.2.9 on 2022-04-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_rename_photo_reservation_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='order_foods',
            field=models.TextField(blank=True, null=True, verbose_name='سفارشات'),
        ),
    ]
